### ISSUE TITLE
Obtaining wl_surface from xwayland window

### ISSUE THREAD

**Issue by AaxAisa** [01org/ozone-wayland#474]
I had seen references several times that Xwayland native window has a wl_surface associated with it.
But I simply can't find a way to do that.

I am a part of the project that can only be run on X11 system, and I need to render directly on the window surface using OpenGL. Unfortunately, we are now tasked to port this application onto Wayland, and I can't render directly onto XWayland surface.

please explain how and if this can be done?

**Comment by rakuco** [comment]
This project has been unmaintained for years, and things have changed a lot in the Chromium code base since then. I suggest either filing a bug in bugs.chromium.org and CC'ing msisov@igalia.com, or sending an email to the [ozone-dev](https://groups.google.com/a/chromium.org/forum/#!forum/ozone-dev) Chromium mailing list.

**Comment by rakuco** [comment]
... although your question doesn't seem to be _that_ specific to Chromium, so you may want to try your luck with the [wayland-devel](https://lists.freedesktop.org/mailman/listinfo/wayland-devel) mailing list itself.
